MainProject/MainProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('demoapp.urls')),
    path('transactions/',include('transactions.urls')),
    path('finance/',include('finance.urls',namespace='finance')),
]

customers/urls.py
from . import views
from django.urls import path
app_name = "customers"
urlpatterns = [
    path('', views.home),
    path('home/' , views.home ,  name = "home"),
    
    path('view_hist/' , views.view_hist , name = "view_hist"),
    path("view_cust/",views.view_cust, name = "view_cust" ),
    path("transfer/" , views.transfer , name = "transfer"),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path,include
from customers import views

urlpatterns = [
    
    path('',include('customers.urls')),
    path('admin/', admin.site.urls),
    
]

customers/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    ids = models.IntegerField(null = False , blank = False )
    name = models.CharField(max_length = 200)
    email = models.EmailField(max_length = 200,unique = True,null = False , blank = False)
    curr_bal = models.DecimalField(decimal_places = 2,max_digits = 8)

class Hist(models.Model):
    
    From = models.EmailField(max_length = 200,unique = True,null = False , blank = False)
    To = models.EmailField(max_length = 200,unique = True,null = False , blank = False)
    amount =  models.DecimalField(decimal_places = 2,max_digits = 8)
    timestamp = models.DateTimeField(auto_now_add=True)

customers/forms.py
from django import forms
from customers.models import Hist
class MoneyTransferForm (forms.ModelForm):
    class Meta:
        model = Hist
        fields = [
            "From",
            "To",
            "amount"

        ]

customers/views.py
from django.shortcuts import render
from customers.models import Customer
from customers.forms import MoneyTransferForm
from django.forms import forms
from django.contrib import messages
from customers.models import Hist
# Create your views here.

def home(request):
    return render(request,"customers/home.html")

def view_cust(request):
    custs = Customer.objects.all()
    return render(request,"customers/details.html",{'customers' : custs})


def transfer(request):
    if request.method == "POST":
        form = MoneyTransferForm(request.POST)
        if (form.is_valid()):
            try:
                user = Customer.objects.get(email=request.POST.get('From'))
                user.curr_bal -= int(request.POST.get('amount'))
                
            except Customer.DoesNotExist:
                user = None
            try:
                userr = Customer.objects.get(email = request.POST.get('To')) 
                userr.curr_bal +=int( request.POST.get('amount'))
                
            except Customer.DoesNotExist:
                userr = None
            if  user == None:
                messages.error(request, "give proper sender email")
                form = MoneyTransferForm()
                context = {'form': form}
                return render(request, "customers/transaction.html", context)
            if int(request.POST.get('amount')) > user.curr_bal:
                messages.error(request,'your transfer amount need to be less than your balance')
                form = forms.MoneyTransferForm()
                context = {'form': form}
                return render(request,"customers/transaction.html",context)
            if int(request.POST.get('amount'))  < 0:
                messages.error(request,"you need to transfer amount greater than 0")
                form = forms.MoneyTransferForm()
                context = {'form': form}
                return render(request,"customers/transaction.html",context)
            if userr == None:
                messages.error(request, "you need to transfer to the correct email")
                form = MoneyTransferForm()
                context = {'form': form}
                return render(request, "customers/transaction.html",context)
            
            form.save()
            user.save()
            userr.save()
            messages.success(request,"Transaction Successfull")
            form = MoneyTransferForm()
            context = {'form': form}
            return render(request,"customers/transaction.html",context)
        else:
            messages.error(request,"you need to give proper details in the fields")
            form = MoneyTransferForm()
            context = {'form': form}
            return render(request,"customers/transaction.html",context)
    else:
        form = MoneyTransferForm()
        context = {'form':form}
        return render(request, "customers/transaction.html",context)

def view_hist(request):
    hists = Hist.objects.all()
    return render(request,"customers/hist_details.html",{'hists' : hists })

templates/customers/details.html
{% extends 'customers/home.html' %}
{% block head %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
{% endblock head %}
{% block content %}

<div class="container">
    <div class="row">
        <table class="col-xs-7 table-bordered table-striped table-condensed table-fixed">
            <thead>
                <tr>
                    <th class = "col">Id</th>
                    <th class="col">Name</th>
                    <th class="col">Email</th>
                    <th class="col">Current Balance</th>
                </tr>
            </thead>
            <tbody>
                
                {% for customer in customers %}
                
                <tr>
                    <td class = "col"> {{ customer.ids }} </td>
                    <td class="col" >{{ customer.name }}</td>
                    <td class="col" >{{ customer.email }}</td>
                    <td class="col" >{{ customer.curr_bal }}</td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
</div>
{% endblock content %}
{% block styles %}
<style>
    .table-fixed {
        margin-left: 25rem;
        margin-top: 10rem;
    }

    .table-fixed thead,
    .table-fixed thead>th {
        background: #4d7275;
        color: #fff;
    }

    .table-fixed tbody tr td {
        background: #fff;
    }

    .table-fixed>thead>tr>th {
        border: 0 !important;
    }

    .table-fixed>tbody>tr>td:last-child {
        border-right: 0;
    }

    .table-fixed tbody td,
    .table-fixed thead>tr>th {
        float: left;
        font-size: 14px;
        padding-left: 20px !important;
    }

    .table-fixed .col {
        width: 25%;
    }

    .table-fixed tbody {
        display: block;
        height: 300px;
        overflow-y: auto;
    }

    .table-fixed tr {
        display: block;
    }
</style>
{% endblock styles %}

templates/customers/hist_details.html
{% extends 'customers/home.html' %}
{% block head %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
{% endblock head %}
{% block content %}

<div class="container">
    <div class="row">
        <table class="col-xs-7 table-bordered table-striped table-condensed table-fixed">
            <thead>
                <tr>
                    
                    <th class="col">From</th>
                    <th class="col">To</th>
                    <th class="col">Amount</th>
		            <th class="col">Date</th>
                </tr>
            </thead>
            <tbody>
                
                {% for hist in hists %}
                
                <tr>
                    
                    <td class="col" >{{ hist.From }}</td>
                    <td class="col" >{{ hist.To }}</td>
                    <td class="col" >{{ hist.amount }}</td>
		    <td class="col" >{{ hist.timestamp }}</td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
</div>
{% endblock content %}
{% block styles %}
<style>
    .table-fixed {
        margin-left: 25rem;
        margin-top: 10rem;
    }

    .table-fixed thead,
    .table-fixed thead>th {
        background: #4d7275;
        color: #fff;
    }

    .table-fixed tbody tr td {
        background: #fff;
    }

    .table-fixed>thead>tr>th {
        border: 0 !important;
    }

    .table-fixed>tbody>tr>td:last-child {
        border-right: 0;
    }

    .table-fixed tbody td,
    .table-fixed thead>tr>th {
        float: left;
        font-size: 14px;
        padding-left: 10px !important;
    }

    .table-fixed .col {
        width: 25%;
    }

    .table-fixed tbody {
        display: block;
        height: 300px;
        overflow-y: auto;
    }

    .table-fixed tr {
        display: block;
    }
</style>
{% endblock styles %}

templates/customers/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% include 'customers/navbar.html'%}
    {% block content %}

    {% endblock %}
    
</body>
{% block styles %}
{% endblock %}
</html>

templates/customers/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="nav">
        <center>
            BASING BANKING SYSTEM
        </center>
    </div>
    <div class="nav2">
        
            <a  href="{% url 'customers:view_cust' %}">View Customers</a>
        
            <a  href = "{% url 'customers:transfer' %}">Make Transaction</a>
            <a  href="{% url 'customers:view_hist' %}">View Transactions</a>
        
    </div>
</body>
<style>
    .nav {
        border: 2px solid rgba(0, 0, 0, 0.123);
        padding: 8px;
        color: rgb(252, 7, 68);
        background-color: rgb(248, 229, 229);
        font-size: 22px;
        border-radius: 7px;
    }

    body {
        background-image: url("/media/reg.jpg");
    }

    .nav2 {
        
        background-color: rgb(216, 236, 30);
        border-radius: 7px;
        position: relative;
        top: 5px;
        height:40px;
        margin-left: 350px;
        width:750px;
    }

   

    a {
        text-decoration: none;
        font-size:20px;
        padding:7px;
        padding-left:15px;
        position: relative;
        left:120px;
        top:10px;
    }
    a:hover
    {
        color: red;
    }

    
</style>

</html>

templates/customers/transaction.html
{% extends 'customers/home.html' %}
{% block content %}
{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
    <p class="font-bold">Error!</p>
    <p class="block sm:inline">{{ error }}</p>
</div>
{% endfor %}
{% endif %}



<div class="container">
<center>
    <form method="post" action="{% url 'customers:transfer' %}">
        {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field }}
        {% endfor %}
       
            <table>
                {% for field in form.visible_fields %}
                <tr>
                    <th>
                        {{ field.label }} :
                    </th>
                    <td>
                        <input name="{{ field.name }}" id="{{ field.id_for_label }}" type="{{ field.widget_type }}"
                            placeholder="Enter {{field.label}}">
                    </td>
                    <br>
                </tr>
            </table>
        
        {% if field.errors %}
        {% for error in field.errors %}
        <p>{{ error }}</p>
        {% endfor %}
        {% endif %}
        {% endfor %}
        <br>
        {{ form.errors }}
        <div class="">
            <button class="" type="submit">
                Transfer
            </button>
        </div>
    </form>

    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</center>
</div>
{% endblock content %}
{% block styles %}
<style>
.container
{
    position: relative;
        top: 40px;
        left:80px;
        border:2px solid red;
        border-radius: 20px;
        padding:20px;
        background-color: azure;
        width: 400px;
        height: 150px;
        padding-right: 60px;
        padding-bottom: 60px;
        margin-left: 450px ;
        height: 250px;
        
}
input
    {
        border:none;
        appearance: none;
        background-color: rgb(255, 255, 255);
        padding:9px;
        border-radius: 5px;
        width:200px;
        border:1px solid rgb(207, 125, 125);
        margin:10px;
        margin-left: 0px;
        margin-right: 0px;
    }
    tr
    {
        margin-top:10px;
    }
</style>

{% endblock styles %}