MainProject/demoapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns=[
    path('',views.Home,name="home"),
    path('logouthome/',views.logouthome,name="logouthome"),
    path('about/',views.about,name="about"),
    path('logoutabout/',views.logoutabout,name="logoutabout"),
    path('ourteam/',views.ourteam,name="ourteam"),
    path('logoutteam/', views.logoutteam, name="logoutteam"),
    path('userlogin/',views.userlogin,name="userlogin"),
    path('userlogout/',views.userlogout,name="userlogout"),
    path('signup/',views.signup,name="signup"),


    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="resetpass.html"),
         name="reset_password"),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="resetpass1.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="resetpass3.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="resetpass2.html"),
         name="password_reset_complete"),

    path('changepwd/',views.changepwd,name='changepwd'),

]

MainProject/finance/urls.py
from django.urls import path
from . import views

app_name = "finance"

urlpatterns = [
    path("loans/",views.loanview,name = "loans"),
    path("loanform/",views.loanform,name = "loanform")
]

MainProject/transactions/urls.py
from django.urls import path
from . import views

app_name = 'transactions'

urlpatterns = [
    # path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("report/", views.trans,name="report"),
    # path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
    path("transfer/",views.transfer,name = "transfer"),
    path("status/",views.status,name="status"),
    path("t_history/",views.t_history,name="t_history"),
    path("l_history/",views.l_history,name="l_history"),
    path("transchart/",views.transchart,name="transchart"),
    path("loanchart/",views.loanchart,name="loanchart"),
]

customers/urls.py
from . import views
from django.urls import path
app_name = "customers"
urlpatterns = [
    path('', views.home),
    path('home/' , views.home ,  name = "home"),
    
    path('view_hist/' , views.view_hist , name = "view_hist"),
    path("view_cust/",views.view_cust, name = "view_cust" ),
    path("transfer/" , views.transfer , name = "transfer"),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path,include
from customers import views

urlpatterns = [
    
    path('',include('customers.urls')),
    path('admin/', admin.site.urls),
    
]

MainProject/demoapp/models.py
from django.db import models

class User(models.Model):
    accountnumber=models.CharField(max_length=15,blank=False,unique=True)
    username = models.CharField(max_length=100, blank=False)
    email=models.EmailField(max_length=30,blank=False)
    password=models.CharField(max_length=20,blank=False)
    accounttype=models.CharField(max_length=20,blank=False,default="savings account")
    ifsc_no = models.CharField(max_length = 6, blank = False , default = "000000")
    bank = models.CharField(max_length = 50 , blank = False , default = "aaaaaa")
    branch = models.CharField(max_length = 50 , blank = False , default = "aaaaa")

    class Meta:
        db_table="user_table"

MainProject/finance/models.py
from django.db import models

# Create your models here.

class Loans(models.Model):
    loan_choices  = (
          ('HomeLoan','HomeLoan'),
          ('EducationLoan','EducationLoan'),
          ('GoldLoan','GoldLoan'),
          ('CarLoan','CarLoan')
      )
    approved_choices = (
        ('approved','approved'),
        ('disapproved','disapproved'),
        ('pending','pending')
    )
    fname=models.CharField(max_length=20,blank=False)
    lname=models.CharField(max_length=20,blank=False)
    username=models.CharField(max_length=50,blank=False)
    mail = models.EmailField (null= False,blank=False,max_length = 30)
    desired_loan_amount = models.IntegerField(null = False)
    annual_income = models.IntegerField(null = False)
    loan_required_for = models.CharField(max_length = 50,choices = loan_choices)
    loan_duration= models.IntegerField(null=False)
    phonenumber = models.BigIntegerField(blank = False,null = False,max_length=10)
    occupation = models.CharField(null = False,max_length=50,blank = False)
    status = models.CharField(max_length=50, choices = approved_choices)
    loan_date = models.DateField(null=True, blank=True)
    intrest = models.DecimalField(decimal_places=2,max_digits=6,null = True, blank=True)
    max_loan=models.IntegerField(blank=False)

MainProject/demoapp/forms.py
from django import forms
from .models import User
class RegistrationForm(forms.ModelForm):
    class Meta:
        model=User
        fields="__all__"

MainProject/finance/forms.py
from django.forms import ModelForm
from .models import Loans

class LoanForm(ModelForm):

    class Meta:
        model=Loans
        fields = [
            "fname",
            "lname",
            "mail",
            "desired_loan_amount",
            "annual_income",
            "loan_required_for",
            "loan_duration",
            "phonenumber",
            "occupation",
            "intrest",
            "max_loan"
        ]

MainProject/transactions/forms.py
import datetime

from django import forms
from django.conf import settings

from .models import  Transactions
from . import models

class TransactionDateRangeForm(forms.Form):
    daterange = forms.CharField(required=False)
    def clean_daterange(self):
        daterange = self.cleaned_data.get("daterange")
        try:
            daterange = daterange.split(' - ')

            if len(daterange) == 2:
                for date in daterange:
                    datetime.datetime.strptime(date, '%Y-%m-%d')
                return daterange
            else:
                raise forms.ValidationError("Please select a date range.")
        except (ValueError, AttributeError):
            raise forms.ValidationError("Invalid date range")

class MoneyTransferForm (forms.ModelForm):
    class Meta:
        model = Transactions
        fields = [
            "ifsc_no",
            "dest_account_number",
            "amount"

        ]

MainProject/demoapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse

from transactions.models import Employee
from .forms import *
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def Home(request):
    return render(request,"home.html")
def logouthome(request):
    username=request.session['username']
    return render(request,"logouthome.html",{'username':username})
def about(request):
    return render(request,"about.html")
def logoutabout(request):
    username = request.session['username']
    return render(request,"logoutabout.html",{'username':username})
def ourteam(request):
    return render(request,"ourteam.html")
def logoutteam(request):
    username = request.session['username']
    return render(request,"logoutteam.html",{'username':username})
def userlogout(request):
    request.session['username']
    del request.session['username']
    messages.info(request,'User logged out')
    return redirect('userlogin')
def userlogin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['pass']
        flag1=Employee.objects.filter(Q(username=username) & Q(password=password))
        if flag1:
            request.session['username'] = username
            return redirect("transactions:t_history")
        flag = User.objects.filter(Q(username=username) & Q(password=password))
        if flag:
            request.session['username'] = username
            return redirect("logouthome")
        else:
            messages.info(request,'Invalid Credentials')
            return redirect("userlogin")
    return render(request, "login.html")
def signup(request):
    f=0
    if request.method == 'POST':
        if request.POST.get('ifsc_no') and request.POST.get('accno') and request.POST.get('username') and request.POST.get('mail') and request.POST.get('pass'):
            s=User()
            s.accountnumber=request.POST.get('accno')
            s.ifsc_no = request.POST.get('ifsc_no')
            ab = s.ifsc_no
            s.username=request.POST.get('username')
            s.email=request.POST.get('mail')
            s.password=request.POST.get('pass')
            a=User.objects.raw('SELECT * from user_table')
            for p in a:
                if p.accountnumber==s.accountnumber or p.username==s.username or p.email==s.email or p.password==s.password:
                    f=1
                    break
            if (f==1):
                messages.error(request,'User already exists')
                return redirect('userlogin')
            else:
                if ab[0:3] ==  "220":
                    s.bank = "SBI"
                    if ab[3:6] == "000":
                        s.branch = "Guntur"
                    elif ab[3:6] == "001":
                        s.branch = "Vijayawada"
                    elif ab[3:6] == "002":
                        s.branch = "Vizag"
                    elif ab[3:6] == "003":
                        s.branch = "Hyderabad"
                    elif ab[3:6] == "004":
                        s.branch = "Amaravathi"
                    elif ab[3:6] == "005":
                        s.branch = "Kakinada"
                    elif ab[3:6] == "006":
                        s.branch = "Machilipatnam"
                    elif ab[3:6] == "007":
                        s.branch = "Secunderabad"
                elif ab[0:3] == "221":
                    s.bank = "HDFC"
                    if ab[3:6] == "000":
                        s.branch = "Guntur"
                    elif ab[3:6] == "001":
                        s.branch = "Vijayawada"
                    elif ab[3:6] == "002":
                        s.branch = "Vizag"
                    elif ab[3:6] == "003":
                        s.branch = "Hyderabad"
                    elif ab[3:6] == "004":
                        s.branch = "Amaravathi"
                    elif ab[3:6] == "005":
                        s.branch = "Kakinada"
                    elif ab[3:6] == "006":
                        s.branch = "Machilipatnam"
                    elif ab[3:6] == "007":
                        s.branch = "Secunderabad"
                elif ab[0:3] ==  "222":
                    s.bank = "AXIS"
                    if ab[3:6] == "000":
                        s.branch = "Guntur"
                    elif ab[3:6] == "001":
                        s.branch = "Vijayawada"
                    elif ab[3:6] == "002":
                        s.branch = "Vizag"
                    elif ab[3:6] == "003":
                        s.branch = "Hyderabad"
                    elif ab[3:6] == "004":
                        s.branch = "Amaravathi"
                    elif ab[3:6] == "005":
                        s.branch = "Kakinada"
                    elif ab[3:6] == "006":
                        s.branch = "Machilipatnam"
                    elif ab[3:6] == "007":
                        s.branch = "Secunderabad"
                elif ab[0:3] ==  "223":
                    s.bank = "CANARA"
                    if ab[3:6] == "000":
                        s.branch = "Guntur"
                    elif ab[3:6] == "001":
                        s.branch = "Vijayawada"
                    elif ab[3:6] == "002":
                        s.branch = "Vizag"
                    elif ab[3:6] == "003":
                        s.branch = "Hyderabad"
                    elif ab[3:6] == "004":
                        s.branch = "Amaravathi"
                    elif ab[3:6] == "005":
                        s.branch = "Kakinada"
                    elif ab[3:6] == "006":
                        s.branch = "Machilipatnam"
                    elif ab[3:6] == "007":
                        s.branch = "Secunderabad"
                elif ab[0:3] ==  "224":
                    s.bank = "UNION"
                    if ab[3:6] == "000":
                        s.branch = "Guntur"
                    elif ab[3:6] == "001":
                        s.branch = "Vijayawada"
                    elif ab[3:6] == "002":
                        s.branch = "Vizag"
                    elif ab[3:6] == "003":
                        s.branch = "Hyderabad"
                    elif ab[3:6] == "004":
                        s.branch = "Amaravathi"
                    elif ab[3:6] == "005":
                        s.branch = "Kakinada"
                    elif ab[3:6] == "006":
                        s.branch = "Machilipatnam"
                    elif ab[3:6] == "007":
                        s.branch = "Secunderabad"
                else:
                    messages.error(request, 'We are not connected with your bank')
                    return redirect('userlogin')


                s.save()
                messages.success(request,'Account was created for ' + s.username)
                return redirect('userlogin')
    return render(request,"signup.html")

def changepwd(request):
    if request.method=='POST':
        opwd=request.POST['opwd']
        npwd=request.POST['npwd']
        username = request.POST['username']
        flag=User.objects.filter(Q(username__iexact=username) & Q(password__iexact=opwd))
        if flag:
            User.objects.filter(username=username).update(password=npwd)
            messages.info(request,'Password updated succesfully')
            return redirect('userlogin')
        else:
            messages.error(request,'Please check the password')
            return redirect('userlogin')
    return render(request,'changepwd.html')

MainProject/finance/views.py
from datetime import date

from django.contrib import messages
from django.shortcuts import render, redirect
from finance.forms import LoanForm
from finance.models import *
# Create your views here.

def loanview(request):
    print("its coming")
    try:
        query = Loans.objects.filter(username = request.session['username'])
    except Loans.DoesNotExist:
        query = None
    context = {'object_list' : query}
    return render(request,'loans.html',context)

def loanform(request):

    if request.method == "POST":
        s=Loans()
        s.fname=request.POST.get('fname')
        s.lname = request.POST.get('lname')
        s.mail = request.POST.get('mail')
        s.desired_loan_amount = int(request.POST.get('loanamt'))
        s.annual_income =int(request.POST.get('income'))
        s.loan_required_for = request.POST.get('type')
        s.loan_duration=int(request.POST.get('time'))
        s.phonenumber=request.POST.get('phno')
        s.occupation=request.POST.get('job')

        if s.loan_required_for == "Home Loan":
            s.intrest=7.0
            s.max_loan=1500000
        elif s.loan_required_for == "Gold Loan":
            s.intrest = 6.5
            s.max_loan = 500000
        elif s.loan_required_for == "Education Loan":
            s.intrest = 6.8
            s.max_loan = 1000000
        else :
            s.intrest = 6.2
            s.max_loan = 800000

        #form= LoanForm(s)
        print("whats happening")
        #for field in form:
        #    print("Field Error:", field.name, field.errors)
        #if form.is_valid():
        #    instance = form.save(commit = False)
        instance=s
        instance.username = request.session['username']
        instance.loan_date = date.today()
            #loa = LoanInfo.objects.get(loan=instance.loan_required_for)
            #instance.intrest = loa.loan_intrest
        if instance.desired_loan_amount <= instance.max_loan:
            a = ((instance.intrest * instance.desired_loan_amount) / 100)*instance.loan_duration
            b = a + instance.desired_loan_amount
            c = b/instance.loan_duration
            d =0.6*instance.annual_income
            if c <= d:
                    instance.status = 'approved'
                    instance.save()
                    #messages.success(request,f"your loan is sactioned")
                    return redirect('finance:loans')
        instance.status = "disapproved"
        instance.save()
        #messages.error(request,f"loan is not sactioned for your requirments")
        return redirect("finance:loans")

        print("whats happening")
        form = LoanForm()
        #context = {'form' : form }

    return render(request,"loanform.html")#,context)

MainProject/templates/loanform.html
{% load static %}

<! DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'loanform.css' %}">
    <title>Loan Application</title>

</head>
<body>

    <div class="navbar">
	<a href="/logouthome">Home</a>
	<a href="{% url 'logoutabout' %}">About</a>
    <div class="dropdown">
    <button class="dropbtn">Banking
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'transactions:status' %}">My Account</a>
      <a href="{% url 'transactions:transfer' %}">Make Transaction</a>
      <a href="{% url 'transactions:report' %}">My Transactions</a>
    </div>
  </div>
        <div class="dropdown">
    <button class="dropbtn">Finance
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'finance:loans' %}">My Loans</a>
      <a href="{% url 'finance:loanform' %}">Apply for a Loan</a>
    </div>
  </div>

    <a href="{% url 'logoutteam' %}">Our Team</a>
	<a href="{% url 'userlogout' %}" class="right">Logout</a>
  </div>

    <div class="container">
        <form method = "post" action = "/finance/loanform/">
            {% csrf_token %}
            <p>Loan Request</p>
            <input class="one" type="text" name="fname" placeholder="Firstname" required autofocus/><br/><br />
            <input class="two" type="text" name="lname" placeholder="Lastname" required/><br /><br />
            <input class="three" type="email" name="mail" placeholder="Email" required /><br/><br />
            <input class="four" type="number" name="loanamt" placeholder="Loan Amount" required/><br /><br />
            <input class="five" type="number" name="income" placeholder="Annual Income" required /><br/><br />

           <select class="spec" id="LoanType" name="type">
                    <option value="1" selected>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp;Loan Type</option>
                    <option value="homeloan" >&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp;Home Loan</option>
                    <option value="goldloan" >&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp;Gold Loan</option>
                    <option value="educationloan" >&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp;Education Loan</option>
                    <option value="carloan" >&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp;Car Loan</option>
                </select><br><br>


            <input class="six" type="number" pattern="[0-1]{1}[0-9]{1}" title="Max duration is 20 years"  name="time" placeholder="Duration(years)" required /><br/><br />
            <input class="seven" type="text" pattern="[0-9]{10}" title="Phone number must be of 10 digits" name="phno" placeholder="Phone Number" required/><br /><br />
            <input class="eight" type="text" pattern="[A-Za-z]{5,}" title="Occupation must use alphabets" name="job" placeholder="Occupation" required /><br/><br />

<!--            <input type="text" name="intrest" id="favourite" placeholder="Intrest" required/><br /><br />-->
<!--            <input type="text" name="maxloan" id="ripe" placeholder="Max Loan" required /><br/><br />-->


            <input type="submit" value="Submit">
        </form>
    </div>

</body>
</html>

MainProject/templates/loans.html
{% load static %}

<! DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" href="{% static 'loans.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <title>Loan Applications</title>
</head>
<body>

    <div class="navbar">
	<a href="/logouthome">Home</a>
	<a href="{% url 'logoutabout' %}">About</a>
    <div class="dropdown">
    <button class="dropbtn">Banking
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'transactions:status' %}">My Account</a>
      <a href="{% url 'transactions:transfer' %}">Make Transaction</a>
      <a href="{% url 'transactions:report' %}">My Transactions</a>
    </div>
  </div>
        <div class="dropdown">
    <button class="dropbtn">Finance
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'finance:loans' %}">My Loans</a>
      <a href="{% url 'finance:loanform' %}">Apply for a Loan</a>
    </div>
  </div>

    <a href="{% url 'logoutteam' %}">Our Team</a>
	<a href="{% url 'userlogout' %}" class="right">Logout</a>
  </div>

     <h1>IP Loan Service</h1>

    <table class="data1">
        <thead class="datahead1">
        <tr class="headrow1">
            <th >Loan Type</th>
            <th >Intrest(%)</th>
            <th >MaximumLoan</th>

        </tr>
        </thead>
        <tbody class="databody1">
        <tr class="bodyrow1">
            <td > Home Loan </td>
            <td > 7.0 </td>
            <td > 15,00,000 </td>
        </tr>
        <tr class="bodyrow2">
            <td > Gold Loan </td>
            <td > 6.5 </td>
            <td > 5,00,000 </td>
        </tr>
        <tr class="bodyrow3">
            <td > Education Loan </td>
            <td > 6.8 </td>
            <td > 10,00,000 </td>
        </tr>
        <tr class="bodyrow4">
            <td > Car Loan </td>
            <td > 6.2 </td>
            <td >  8,00,000 </td>
        </tr>
        </tbody>
    </table>

    <h1 class="one">Your Applications</h1>
    <table class="data" >
        <thead class="datahead">
        <tr class="headrow">
            <th >Loan Type</th>
            <th >Amount</th>
            <th >Intrest</th>
            <th >Status</th>
        </tr>
        </thead>
        <tbody class="databody">
        {% for loan in object_list %}
        <tr class="bodyrow">
            <td >{{ loan.loan_required_for }}</td>
            <td >{{ loan.desired_loan_amount }}</td>
            <td >{{ loan.intrest }}</td>
            <td > {{ loan.status }}</td>
        </tr>
        {% endfor %}

        </tbody>
    </table>

</body>
</html>

MainProject/templates/login.html
{% load static %}

<! DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <title>IP User Login</title>
</head>
<body>
    <div class="navbar">
	<a href="/">Home</a>
	<a href="{% url 'about' %}">About</a>
	<a href="/userlogin">Banking</a>
	<a href="/userlogin">Finance</a>
    <a href="{% url 'ourteam' %}">Our Team</a>
	<a href="{% url 'userlogin' %}" class="right">Login/Signup</a>
  </div>

    <div class="container">
        <p>LOGIN</p>

        <form action="{% url 'userlogin' %}" method="post" name="f1">
            {% for message in messages %}
                <span>{{message}}</span>
            {% endfor %}<br>
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username" required autofocus/><br/><br />
            <input type="password" name="pass" placeholder="password" required/><br /><br />
            <input type="submit" value="Log In">
            <br /><br />
            <div id="container">
            <a href="{% url 'reset_password' %}">Forgot password</a>
            &nbsp&nbsp&nbsp<a href="{% url 'changepwd' %}">Reset password</a>
            </div><br />
            <span>Don't have an account?</span><a href="{% url 'signup' %}">&nbsp;Sign Up</a>
        </form>
    </div>
</body>
</html>

MainProject/templates/logoutteam.html
{% load static %}

<! DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'ourteam.css' %}">
    <link rel="stylesheet" href="{% static 'all.css'%}">
    <script defer src="{% static 'all.js'%}"></script>
    <title>IP Developer Team</title>
</head>
<body>
    <div class="navbar">
	<a href="/logouthome">Home</a>
	<a href="{% url 'logoutabout' %}">About</a>
    <div class="dropdown">
    <button class="dropbtn">Banking
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'transactions:status' %}">My Account</a>
      <a href="{% url 'transactions:transfer' %}">Make Transaction</a>
      <a href="{% url 'transactions:report' %}">My Transactions</a>
    </div>
  </div>
        <div class="dropdown">
    <button class="dropbtn">Finance
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'finance:loans' %}">My Loans</a>
      <a href="{% url 'finance:loanform' %}">Apply for a Loan</a>
    </div>
  </div>

    <a href="{% url 'logoutteam' %}">Our Team</a>
	<a href="{% url 'userlogout' %}" class="right">Logout</a>
  </div>

    <div class="dev-1">
        <p class="name-1">KOMMURU KARTHIK</p>
        <div class="overlay">
            <div class="text">
                <p>Team Member</p>
                <p>Developer</p>
                <a href="#"><i class="fab fa-facebook"></i></a>
				<a href="#"><i class="fab fa-instagram"></i></a>
				<a href="#"><i class="fab fa-twitter"></i></a>
				<a href="#"><i class="fas fa-envelope"></i></a>
            </div>
        </div>
    </div>

    <div class="dev-2">
        <p class="name-2">K RATHNA SAI</p>
        <div class="overlay-2">
            <div class="text-2">
                <p>Team Leader</p>
                <p>Developer/Maintainer</p>
                <a href="#"><i class="fab fa-facebook"></i></a>
				<a href="#"><i class="fab fa-instagram"></i></a>
				<a href="#"><i class="fab fa-twitter"></i></a>
				<a href="#"><i class="fas fa-envelope"></i></a>
            </div>
        </div>
    </div>

    <div class="dev-3">
        <p class="name-3">CH SAI NITEESH</p>
        <div class="overlay-3">
            <div class="text-3">
                <p>Team Member</p>
                <p>Developer</p>
                <a href="#"><i class="fab fa-facebook"></i></a>
				<a href="#"><i class="fab fa-instagram"></i></a>
				<a href="#"><i class="fab fa-twitter"></i></a>
				<a href="#"><i class="fas fa-envelope"></i></a>
            </div>
        </div>
    </div>



</body>
</html>

MainProject/templates/resetpass1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reset Password</title>
</head>
<body>
    <h3>Password reset sent</h3>

    <p>We’ve emailed you instructions for setting your password,
        if an account exists with the email you entered. You should receive them shortly.</p>

    <p>If you don’t receive an email,
        please make sure you’ve entered the address you registered with, and check your spam folder.</p>

</body>
</html>

MainProject/templates/status.html
{% load static %}

<! DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'status.css' %}" rel="stylesheet">
    <title>IP Status</title>
</head>
<body>
   <div class="navbar">
	<a href="/logouthome">Home</a>
	<a href="{% url 'logoutabout' %}">About</a>
    <div class="dropdown">
    <button class="dropbtn">Banking
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'transactions:status' %}">My Account</a>
      <a href="{% url 'transactions:transfer' %}">Make Transaction</a>
      <a href="{% url 'transactions:report' %}">My Transactions</a>
    </div>
  </div>
        <div class="dropdown">
    <button class="dropbtn">Finance
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="{% url 'finance:loans' %}">My Loans</a>
      <a href="{% url 'finance:loanform' %}">Apply for a Loan</a>
    </div>
  </div>

    <a href="{% url 'logoutteam' %}">Our Team</a>
	<a href="{% url 'userlogout' %}" class="right">Logout</a>
  </div>

    <div class="container">
        <p>Details</p>
        <div class="one">
            <span class="uname"> Username</span>
            {{ curr_user.username }}<br>
        </div>
        <div class="two">
            <span class="num">Account Number</span>
            {{ curr_user.account_no }}<br>
        </div>
        <div class="three">
            <span class="bal">Balance</span>
            {{ curr_user.balance }}<br>
        </div>
    </div>

</body>
</html>